<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gloire  lHomme Fort famille</name>
   <tag></tag>
   <elementGuidId>768856ba-1ef2-4a8c-8a6f-8eab96ac247d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/footer/div/div/span[2]/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._3Uu1_ > div.g0rxnol2.ln8gz9je.lexical-rich-text-input > div.to2l77zo.gfz4du6o.ag5g9lrv.bze30y65.kao4egtt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Taper un message' and @data-testid = 'conversation-compose-box-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e7157c1-9398-419d-91a4-78b37ab6f322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>to2l77zo gfz4du6o ag5g9lrv bze30y65 kao4egtt</value>
      <webElementGuid>93c4894f-e4e4-4c07-945f-53697f52b148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>af098d8e-70cb-487a-a542-1f185a69640a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>cfc4588b-cf14-4d54-86c1-faf88a3d9617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>baec0810-a0ff-4aef-bc35-5357e20419d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Taper un message</value>
      <webElementGuid>e5407167-b9f7-4ab0-a023-d1468a8cfe28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>conversation-compose-box-input</value>
      <webElementGuid>89d79884-9da5-45e6-a4d0-4b20c69c2256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>50cf3fe0-02dc-4535-8cc7-73a6f6b016aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6922e764-df0e-469d-9f1a-8286861aa002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lexical-editor</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ae14633-73c2-41c6-a70c-45172f65880e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gloire à l'Homme Fort famille</value>
      <webElementGuid>f4e951e9-9f2f-44d2-b9ce-0191054471e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/footer[@class=&quot;_3E8Fg&quot;]/div[@class=&quot;_2lSWV _3cjY2 copyable-area&quot;]/div[@class=&quot;_4r9rJ&quot;]/span[2]/div[@class=&quot;_2lryq&quot;]/div[@class=&quot;_1VZX7&quot;]/div[@class=&quot;_3Uu1_&quot;]/div[@class=&quot;g0rxnol2 ln8gz9je lexical-rich-text-input&quot;]/div[@class=&quot;to2l77zo gfz4du6o ag5g9lrv bze30y65 kao4egtt&quot;]</value>
      <webElementGuid>2988a88c-31cc-4227-bfc0-0bb3de137265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/footer/div/div/span[2]/div/div[2]/div/div/div</value>
      <webElementGuid>88691954-fefd-4f3a-bae8-731e8730b2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amen le bic singa noa koa de 9 ?'])[2]/following::div[23]</value>
      <webElementGuid>209eae3a-fa64-467d-b133-45870b038841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pa Alain Bonaberi'])[2]/following::div[25]</value>
      <webElementGuid>51e98f6a-9926-4748-9fa6-eac2fcfdfca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infos du contact'])[1]/preceding::div[15]</value>
      <webElementGuid>f412bb3d-3451-4f21-bc38-a9a8d6be9d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/div[2]/div/div/div</value>
      <webElementGuid>38ef6dcf-a29c-4a72-8f15-7e928f5278f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Taper un message' and (text() = concat(&quot;Gloire à l&quot; , &quot;'&quot; , &quot;Homme Fort famille&quot;) or . = concat(&quot;Gloire à l&quot; , &quot;'&quot; , &quot;Homme Fort famille&quot;))]</value>
      <webElementGuid>db14ce69-d4e7-4eaa-a964-11d89d0597a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
