<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>a7657b81-b126-4afb-8267-2240d707cc04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/footer/div/div/span[2]/div/div[2]/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tvf2evcx.oq44ahr5.lb5m6g5c.svlsagor.p2rjqpw5.epia9gcq > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a06d4df0-2169-4463-a91e-3ba5b6215b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>send</value>
      <webElementGuid>b34b0c4e-7752-4284-b2ed-17cf07a30fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>send</value>
      <webElementGuid>e5842733-8842-4ada-ba15-d15d631b01c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/footer[@class=&quot;_3E8Fg&quot;]/div[@class=&quot;_2lSWV _3cjY2 copyable-area&quot;]/div[@class=&quot;_4r9rJ&quot;]/span[2]/div[@class=&quot;_2lryq&quot;]/div[@class=&quot;_1VZX7&quot;]/div[@class=&quot;_2xy_p _3XKXx&quot;]/button[@class=&quot;tvf2evcx oq44ahr5 lb5m6g5c svlsagor p2rjqpw5 epia9gcq&quot;]/span[1]</value>
      <webElementGuid>52920762-8a0d-469d-a070-43b0f489f4b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/footer/div/div/span[2]/div/div[2]/div[2]/button/span</value>
      <webElementGuid>1cad2306-3e6d-4e2d-9404-ebfbfe481beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Gloire à l', &quot;'&quot;, 'Homme Fort famille')])[1]/following::span[1]</value>
      <webElementGuid>69e78565-4261-44d3-9e2d-4cdd0ae55edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amen le bic singa noa koa de 9 ?'])[2]/following::span[15]</value>
      <webElementGuid>7db47893-b4e7-49ae-85cc-d62496c3b716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infos du contact'])[1]/preceding::span[3]</value>
      <webElementGuid>d57c49c6-4b24-41f6-9d81-411f0ce6473d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ndongo MTN'])[5]/preceding::span[3]</value>
      <webElementGuid>2272f404-faf5-4bd2-9756-1638f47920bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>88923b7c-115c-4aa2-b9b6-ced1d7f6d6e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
